<a href="https://colab.research.google.com/github/ezypzylemon/12month/blob/main/0116_%EC%8B%9C%EA%B7%B8%EB%AA%A8%EC%9D%B4%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 시그모이드 함수와 그 도함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# 입력 데이터 (4개의 특성을 가진 4개의 샘플)
X = np.array([
    [0, 0, 0, 1],
    [0, 0, 1, 1],
    [0, 1, 0, 1],
    [0, 1, 1, 1]
])

# 실제값 (AND  문제의 예시)
Y = np.array([[0], [0], [0], [1]])


In [3]:
# 가중치 초기화 (랜덤값으로 설정)
import numpy as np
np.random.seed(1)

w1 = np.random.randn(4, 3)  # 입력 -> 은닉층 가중치 (4 -> 3)------------> (input_shape=(4,), activation='relu')

b1 = np.random.randn(1, 3)  # 은닉층 바이어스

w2 = np.random.randn(3, 1)  # 은닉층 -> 출력층 가중치 (3 -> 1)
b2 = np.random.randn(1)     # 출력층 바이어스

print(w1, b1)


[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]] [[-0.3224172  -0.38405435  1.13376944]]


In [4]:
# 학습률 , 1000, 100, 10, 1, 0.1, 0.01, 0.001 이런식으로 가는것을 추천 잘 맞추면 오차의 갱신률을 완만하게 잘 못 맞추면 급하게
learning_rate = 0.1

In [5]:
z1 = np.dot(X, w1) + b1 # 은닉층 입력       #np.dot -> 내적곱임
h = sigmoid(z1) # 은닉층 출력 (활성화함수 적용)

print(z1)

[[-0.57178758  1.07805358 -0.92637127]
 [ 1.17302418  0.31684668 -0.60733217]
 [-1.6447562   1.94346121 -3.22790996]
 [ 0.10005556  1.18225431 -2.90887087]]


In [8]:
    z2 = np.dot(h, w2) + b2 # 출력층 입력
    y_pred = sigmoid(z2) # 출력층 예측값 (활성화함수 적용)
    y_pred

array([[0.32468547],
       [0.23021184],
       [0.42065878],
       [0.32902681]])

In [10]:
#손실함수 (Mean Squared Error)
loss = np.mean((y_pred - Y) ** 2)
loss

0.19639424464896765

In [11]:
y.size


4

In [12]:
# 역전파 (Backpropagation)
# 출력층에서의 기울기
d_loss_d_y_pred = -2 * (y_pred - y) / y.size  # 손실 함수의 출력에 대한 기울기
d_y_pred_d_z2 = sigmoid_derivative(y_pred)   # 시그모이드 함수의 도함수
d_z2_d_w2 = h                                # z2를 w2에 대한 미분한 값 (h)
